config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles do
    resources :comments, only: [:create, :destroy]
  end

  post '/new_user_reaction', to: 'reactions#new_user_reaction', as: 'new_user_reaction'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    # Associations
    belongs_to :user
    has_many :reactions, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_one_attached :image

    # Validations
    validates :title, presence: true
    validates :description, presence: true

    Kinds = %w[like dislike not_interested neutral].freeze
    KindsSpanish = {"like" => "Me gusta", "dislike" => "No me gusta", "not_interested" => "No me interesa", "neutral" => "Neutral"}.freeze
    ReactionsIcons = {
        "like" => "fas fa-thumbs-up",
        "dislike" => "fas fa-thumbs-down",
        "not_interested" => "fas fa-meh",
        "neutral" => "fas fa-circle"
      }.freeze
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :article
  has_many :reactions, dependent: :destroy

  # Validations
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :article, optional: true
  belongs_to :comment, optional: true

  # Validations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  has_many :articles, dependent: :destroy
  has_many :reactions
  has_many :comments

  # Validations

  enum role: { user: 0, admin: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :set_user, except: %i[ index show ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :image)
    end

    def set_user
      @user = current_user
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.build(comment_params)
        @comment.user = current_user
    
        if @comment.save
            redirect_to @article, notice: 'Comentario agregado correctamente.'
          else
            render 'articles/show'
          end
    end

    def destroy
        @comment = Comment.find(params[:id])

        if current_user == @comment.user || current_user == @comment.article.user || current_user.admin?
            @comment.destroy
            redirect_to @comment.article, notice: 'Comentario eliminado correctamente.'
          else
            redirect_to @comment.article, alert: 'No tienes permiso para eliminar este comentario.'
          end
    end

    private
    def comment_params
        params.require(:comment).permit(:content)
    end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  def new_user_reaction
    @user = current_user
    @type = params[:reaction_type]
    @article = Article.find(params[:article_id]) if params[:article_id]
    @comment = Comment.find(params[:comment_id]) if params[:comment_id]
    @kind = params[:kind]

    reaction = if @type == "comment"
                 @user.reactions.find_by(comment_id: @comment.id)
               else
                 @user.reactions.find_by(article_id: @article.id)
               end

    respond_to do |format|
      if reaction
        # Actualizar la reacción existente si se cambia
        reaction.update(kind: @kind) if reaction.kind != @kind
        format.html { redirect_to request.referrer, notice: 'Reacción actualizada exitosamente.' }
      else
        reaction_params = {
          user_id: @user.id,
          reaction_type: @type,
          kind: @kind
        }
        reaction_params[@type == "comment" ? :comment_id : :article_id] = @type == "comment" ? @comment.id : @article.id

        @reaction = Reaction.new(reaction_params)

        if @reaction.save
          format.html { redirect_to request.referrer, notice: 'La reacción fue creada exitosamente!.' }
        else
          format.html { redirect_to request.referrer, notice: 'Un error ha ocurrido!' }
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_class?(test_path)
        return 'active' if request.path == test_path
        ''
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<article id="<%= dom_id article %>">
  <!-- article header-->
  <header class="mb-4">
    <!-- article title-->
    <h1 class="fw-bolder mb-1"><%= article.title %></h1>
    <!-- article meta content-->
    <div class="text-muted fst-italic mb-2">Actualizado el <%= article.updated_at.strftime("%d/%m/%Y") %> a las <%= article.updated_at.strftime("%H:%M") %> hrs. Autor: <%= article.user.email %></div>
    <!-- article categories-->
    <%# <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a> %>
  </header>
  <!-- Preview image figure-->
  <figure class="mb-4">
  <% if article && article.image.attached? %>
    <%= image_tag article.image, class: "img-fluid rounded" %>
  <% else %> 
    <%= image_tag "https://dummyimage.com/900x400/ced4da/6c757d.jpg", class: "img-fluid rounded" %>
  <% end %>
  <%# <img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /> %>
  </figure>
  <!-- article content-->
  <section class="mb-5">
    <p class="fs-5 mb-4"><%= article.description %></p>
    <%# < class="fs-5 mb-4"><%= article.content %>
  </section>
</article>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<h1 class="mt-2 mb-2 text-center">Últimas Publicaciones</h1>

<%= link_to "Nueva Publicación", new_article_path, class: "btn btn-success" %>
<div class="col-lg-8 col-md-10 mx-auto">
  <!-- Article content-->
  <% @articles.each do |article| %>
    <div class="article">
      <%= render article %>
      <p><%= link_to "Ver más", article, class: "btn btn-primary my-1" %></p>
      <div class="btn-group" role="group">
        <% Article::Kinds.each do |kind| %>
          <% total_reactions = article.reactions.where(kind: kind).count %>
          <% user_reaction = current_user.reactions.find_by(article_id: article.id, kind: kind) %>
          <% icon_class = Article::ReactionsIcons[kind] %>

          <% button_class = user_reaction&.kind == kind ? "btn btn-success" : "btn btn-primary" %>

          <%= button_to "<i class='#{icon_class}'></i> #{Article::KindsSpanish[kind]} (#{total_reactions})".html_safe, new_user_reaction_path(article_id: article.id, reaction_type: "article", kind: kind), method: :post, class: button_class %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<%= link_to "Back to articles", articles_path, class: "btn btn-primary my-1" %>

<%= render @article %>

<% if user_signed_in? %>
  <% if current_user.admin? || current_user == @article.user %>
    <div>
      <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-primary" %>
      <%= button_to "Destroy this article", @article, method: :delete, data: { confirm: "Estas seguro?" }, class: "btn btn-danger my-2" %>
    </div>
  <% end %>
<% end %>

  <hr>

<h2>Reacciones:</h2>

<div class="btn-group" role="group">
  <% Article::Kinds.each do |kind| %>
    <% total_reactions = @article.reactions.where(kind: kind).count %>
    <% user_reaction = current_user.reactions.find_by(article_id: @article.id, kind: kind) %>
    
    <% icon_class = Article::ReactionsIcons[kind] %>
    <% button_class = user_reaction&.kind == kind ? "btn btn-success" : "btn btn-primary" %>

    <%= button_to "<i class='#{icon_class}'></i> #{Article::KindsSpanish[kind]} (#{total_reactions})".html_safe, new_user_reaction_path(article_id: @article.id, reaction_type: kind, kind: kind), method: :post, class: button_class %>
  <% end %>
</div>


<h2>Comentarios:</h2>

<%= render "comments/comments" %>

app/views/comments/_comment.html.erb
<div class="d-flex mb-1">
  <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
  <div class="ms-3">
    <div class="fw-bold"><%= comment.user.email %> dice:</div>
    <div class="comment">
      <p>
      <%= comment.content %> <span class="text-muted fst-italic mb-2 comentario-fecha"><%= comment.created_at.strftime("%d/%m/%Y %H:%M")%></span>
        <% if user_signed_in? && (current_user == comment.user || current_user.admin?) %>
          <%= link_to "X", [comment.article, comment], method: :delete, data: { confirm: '¿Estás seguro de que deseas eliminar este comentario?', turbo_method: :delete }, class: "btn btn-danger borrar-comentario" %>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/comments/_comments.html.erb
  <section class="mb-5">
        <div class="card bg-light">
            <div class="card-body">
                <!-- Comentario individual-->
                <% @article.comments.each do |comment| %>
                    <%= render comment %>
                <% end %>

                <% if user_signed_in? %>
                    <!-- Formulario-->
                    <%= render "comments/form" %>
                <% else %>
                    <p class="m-2"><strong>Debes iniciar sesión para comentar.</strong></p>
                <% end %>
            </div>
        </div>
    </section>

app/views/comments/_form.html.erb
  <%= form_for([@article, Comment.new], :html => {:class => "mt-4"}) do |f| %>
    <%= f.text_area :content, placeholder: 'Unete a la conversación y deja un comentario...', class: "form-control" %>
    <%= f.submit 'Comentar', class: "btn btn-primary mt-2" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazy4Cats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flash" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-dismissible fade show alert-warning d-flex align-items-center alert-<%= key %>" role="alert">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
    </svg>
    <%= value %>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark"> 
  <div class="container-fluid">
    <%= link_to "Crazy4Cats", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Inicio", root_path, class: "nav-link #{current_class?(root_path)}", aria: { current: "page" } %>
        </li>

        <%# Dropdown inicio sesion y registro %>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= link_to current_user.email, "#", class: "nav-link dropdown-toggle", data: { "bs-toggle" => "dropdown"}, role: "button", aria: { expanded: "false" } %>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Editar perfil", edit_user_registration_path, class:"dropdown-item" %>
              </li>
              <li>
                <%= button_to "Cerrar sesión", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <%= link_to "Ingresar", "#", class: "nav-link dropdown-toggle", data: { "bs-toggle" => "dropdown"}, role: "button", aria: { expanded: "false" } %>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Registrate", new_user_registration_path, class:"dropdown-item" %>
              </li>
              <li>
                <%= link_to "Iniciar sesión", new_user_session_path, class:"dropdown-item" %>
              </li>
            </ul>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>